# Neural networks using Keras

In [4]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Flatten, Dropout

A single input model with 2 classes (binary classification)

In [5]:
model = Sequential()
hidden_layer = Dense(32, activation='relu', input_dim = 100)
model.add(hidden_layer)
output_layer = Dense(1, activation='sigmoid')
model.add(output_layer)
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [6]:
import numpy as np

In [15]:
data = np.random.random((1000, 100)) #1000 rows and 100 columns
labels = np.random.randint(2, size=(1000,1))  #binary output

In [17]:
model.fit(data, labels)

Epoch 1/1
1000/1000 [==============================] - 0s 214us/step - loss: 0.7080 - acc: 0.5210


In [21]:
(data[0]).shape

(100,)

A single input model with 2 classes and a feature space of 16 (n = 16)

In [22]:
model = Sequential()
hidden_layer = Dense(10, activation='relu', input_dim = 16)
model.add(hidden_layer)
output_layer = Dense(1, activation='sigmoid')
model.add(output_layer)
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [23]:
data = np.random.random((1000, 16)) #1000 rows and 100 columns
labels = np.random.randint(2, size=(1000,1))  #binary output

In [24]:
model.fit(data, labels)

Epoch 1/1
1000/1000 [==============================] - 0s 134us/step - loss: 0.7017 - acc: 0.4890


A single input model with 4 classes and a feature space of 50

In [25]:
c

In [27]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 32)                1632      
_________________________________________________________________
dense_6 (Dense)              (None, 4)                 132       
Total params: 1,764
Trainable params: 1,764
Non-trainable params: 0
_________________________________________________________________


In [28]:
data = np.random.random((1000, 50)) #1000 rows and 100 columns
labels = np.random.randint(4, size=(1000,4))  #binary output

In [29]:
model.fit(data, labels)

Epoch 1/1
1000/1000 [==============================] - 0s 141us/step - loss: -0.1717 - acc: 0.2440


A single input model with 4 classes and a feature space of 16

In [38]:
data = np.random.random((2, 16)) #1000 rows and 100 columns
labels = np.random.randint(4, size=(2,4))  #binary output

In [41]:
model = Sequential()
hidden_layer = Dense(10, activation='relu', input_dim = 16)
model.add(hidden_layer)
output_layer = Dense(4, activation='sigmoid')
model.add(output_layer)
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [42]:
model.fit(data, labels)

Epoch 1/1
2/2 [==============================] - 0s 88ms/step - loss: 0.6675 - acc: 0.0000e+00


In [49]:
model = Sequential()
model.add(Dense(10, input_dim=16, activation = 'relu'))
model.add(Dense(4, activation='sigmoid'))
model.compile(optimizer='rmsprop',
          loss='mse')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 10)                170       
_________________________________________________________________
dense_14 (Dense)             (None, 4)                 44        
Total params: 214
Trainable params: 214
Non-trainable params: 0
_________________________________________________________________


In [101]:
state = 5
input_vector = np.array(np.zeros((1,16)))
input_vector[:,state] = 1
# action = self.q.predict(input_vector)

In [102]:
model.predict(input_vector)

array([[ 0.51743859,  0.45925629,  0.44995871,  0.55107951]], dtype=float32)

In [98]:
state = 4
input_vector = np.zeros((1, 16))
input_vector[:,state] = 1
input_vector

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.]])

In [89]:
a = np.ones((4,5))
print(a)
a.shape
a[2:3,] = 6
a

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [59]:
np.random.random((1, 16))

array([[ 0.01555607,  0.76267933,  0.81532111,  0.13720076,  0.95329434,
         0.55612073,  0.62834149,  0.17455435,  0.60903547,  0.0820639 ,
         0.20630015,  0.6110506 ,  0.77755914,  0.20608216,  0.80607383,
         0.29189015]])

In [53]:
action =model.predict(input_vector)

ValueError: Error when checking : expected dense_13_input to have shape (16,) but got array with shape (1,)